name: hydrotower_app
description: "App di monitoraggio per la torre idroponica HydroTower"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.4.0
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.5.5
  google_fonts: ^8.2.1
  flutter_tts: ^4.0.2
  image_picker: ^1.1.2
  vibration: ^3.2.0
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0
  flutter_local_notifications: ^22.3.0
  file_picker: ^10.3.3
  flutter_secure_storage: 10.3.2
  mobile_scanner: ^7.1.2
  flutter_tabler_icons: ^1.43.0
  wireguard_flutter_plus: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
